server:
  port : 8089
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ewaDatabase
    username: root
    password: admin
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

